### ISSUE TITLE
Cloudformation error 500 when running: sls deploy

### ISSUE THREAD

**Issue by blai** [localstack/serverless-localstack#33]
Consistently running into this cloudformation issue when running `sls deploy` over plain helloworld Serverless example (generated using `sls create -t aws-go`) with all default settings as described in README

```
❯ SLS_DEBUG=* sls deploy --stage=local
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
(node:89480) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Serverless: Using serverless-localstack
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Skip plugin function AwsCompileFunctions.downloadPackageArtifacts (lambda.mountCode flag is enabled)
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.039s 0 retries] describeStacks({ StackName: 'sls-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.172s 0 retries] createStack({
  StackName: 'sls-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.115s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:000000000000:stack/sls-local/90777dd6-27f1-4c33-93f4-22e6f8e51065'
})
.
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.015s 0 retries] describeStackResource({
  StackName: 'sls-local',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.023s 0 retries] listObjectsV2({
  Bucket: 'sls-local-ServerlessDeploymentBucket-0A-Z6675022236',
  Prefix: 'serverless/sls/local'
})
Serverless: [AWS sts 200 0.02s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.015s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 5710 more bytes>,
  Bucket: 'sls-local-ServerlessDeploymentBucket-0A-Z6675022236',
  Key: 'serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 't/5b63d0vXNIzrMIYQ9BLYzcDbWJU8PWegwZEsNtsjg=' }
})
Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: [AWS cloudformation 500 0.982s 3 retries] updateStack({
  StackName: 'sls-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-local-ServerlessDeploymentBucket-0A-Z6675022236/serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 500 0.823s 3 retries] updateStack({
  StackName: 'sls-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-local-ServerlessDeploymentBucket-0A-Z6675022236/serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 500 0.759s 3 retries] updateStack({
  StackName: 'sls-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-local-ServerlessDeploymentBucket-0A-Z6675022236/serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 500 1.007s 3 retries] updateStack({
  StackName: 'sls-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-local-ServerlessDeploymentBucket-0A-Z6675022236/serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 500 0.961s 3 retries] updateStack({
  StackName: 'sls-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-local-ServerlessDeploymentBucket-0A-Z6675022236/serverless/sls/local/1564692633187-2019-08-01T20:50:33.187Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ]
})

  Serverless Error ---------------------------------------

  500

  Stack Trace --------------------------------------------

ServerlessError: 500
    at /Users/blai/.nvm/versions/node/v12.5.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:316:27
    at processTicksAndRejections (internal/process/task_queues.js:82:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           12.5.0
     Serverless Version:     1.47.0
```

**Comment by odelucca** [comment]
This is a duplicate of this: https://github.com/localstack/serverless-localstack/issues/3

**Comment by blai** [comment]
#3 says socket hang up, so not sure if the cause is the same, though from high level they look similar.

**Comment by IvanBernatovic** [comment]
I'm trying to deploy my app to localstack and I'm getting the same errors. Is there any workaround or any useful info?

**Comment by whummer** [comment]
This should be fixed in https://github.com/localstack/localstack/pull/1504 . Can you please give it a try with the `latest` version of the Docker image, as well as version `^0.4.19` of `serverless-localstack`?

**Comment by whummer** [comment]
Closing for now - please re-open if the problem persists. Thanks

**Comment by blai** [comment]
@whummer problem persisted with `^0.4.19` and latest docker image 
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              8a612c27347a        45 hours ago        804MB
```

**Comment by whummer** [comment]
@blai Any updates on this issue? Can you please provide the latest error logs (from Serverless, and LocalStack) when running this sample?

**Comment by lunae** [comment]
New to localstack and running into a similar issue. I noticed that for some reason the during the sls deploy, the CF template is trying to be fetched from an S3 bucket in AWS `https://s3.amazonaws.com` instead of `http://localhost:4572`. Navigating to the URL with localhost:4572 the template is found. I also tried setting HOSTNAME_EXTERNAL=localhost explicitly but still running into the same issue. Hope this helps.

**Comment by pjmeisch-cc** [comment]
same problem here with latest versions

**Comment by blai** [comment]
tried today, it works now. I've upgrade Docker and Minikube in the past month, not sure what changed, the localstack docker image version is the same this time.

**Comment by blai** [comment]
BTW, `sls remove --stage local` still doesn't work, the issue seems to be similar
```
...
Serverless: Invoke remove
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: config.stage: local
Serverless: [AWS cloudformation 500 0.277s 3 retries] describeStackResource({ StackName: 'sls-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: [AWS cloudformation 500 0.282s 3 retries] describeStackResource({ StackName: 'sls-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
Serverless: [AWS cloudformation 500 0.575s 3 retries] describeStackResource({ StackName: 'sls-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 3 of 4
Serverless: [AWS cloudformation 500 0.541s 3 retries] describeStackResource({ StackName: 'sls-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
Serverless: [AWS cloudformation 500 0.287s 3 retries] describeStackResource({ StackName: 'sls-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
...
```

**Comment by certara-yloginov** [comment]
Same issue:
`serverless deploy --verbose --stage local
Serverless: Using serverless-localstack
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Recoverable error occurred (500), sleeping for ~5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (500), sleeping for ~7 seconds. Try 2 of 4
Serverless: Recoverable error occurred (500), sleeping for ~5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (500), sleeping for ~6 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  500

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.2
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        2.30.11`

**Comment by JoshuaAlzate** [comment]
> New to localstack and running into a similar issue. I noticed that for some reason the during the sls deploy, the CF template is trying to be fetched from an S3 bucket in AWS `https://s3.amazonaws.com` instead of `http://localhost:4572`. Navigating to the URL with localhost:4572 the template is found. I also tried setting HOSTNAME_EXTERNAL=localhost explicitly but still running into the same issue. Hope this helps.

Were you able to resolve this?
